if: tag IS present

language: generic
sudo: required

env:
  global:
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64

matrix:
  include:
    - os: linux
      services:
        - docker
      env: MB_PYTHON_VERSION=3.5
    - os: linux
      services:
        - docker
      env: MB_PYTHON_VERSION=3.6
    - os: linux
      services:
        - docker
      env: MB_PYTHON_VERSION=3.7
    - os: linux
      services:
        - docker
      env: MB_PYTHON_VERSION=3.8
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.5
        - PLAT=x86_64
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.6
        - PLAT=x86_64
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.7
        - PLAT=x86_64
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.8
        - MB_PYTHON_OSX_VER=10.9
        - MB_ML_VER=2010

before_install: |
  set -e
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    docker pull $DOCKER_IMAGE
  elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    source multibuild/common_utils.sh
    source multibuild/travis_steps.sh
    before_install
  fi


install: |
  # Output something every 10 minutes or Travis kills the job
  while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  bg_pid=$!
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/build-linux-wheels.sh $MB_PYTHON_VERSION
  elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    export MYPY_USE_MYPYC=1
    export MYPYC_OPT_LEVEL=3
    # Note: The following functions are defined by multibuild
    clean_code mypy HEAD
    build_bdist_wheel mypy x86_64
    (cd mypy && ./misc/test_installed_version.sh ../wheelhouse/*.whl)
  fi
  kill $bg_pid

notifications:
  email:
    recipients:
      - sully@msully.net
    on_success: never # default: change
    on_failure: always # default: always

deploy:
  provider: releases
  api_key:
    secure: KM6lZpvVJ36DNXgCOrnN9CrD+e2Ed9PkR8Ij8aLOzMKiq7+blhWRyA4ZEuF0N0zTiN29nmpKBsC1Qz4II/kZSAFrJQKf32ef67ypQ0XFCJYw4rqgsOcuZqfBf+ZqHVv3IWU3Kb33GoOysG945TyFQ3JFEeN0hWRUtVm8Tav0ths9Ut2+GyOt/jGn+qRcG6xqqt069f65eXC+sGSwcuVlqb1x2kLT31AKOQzMMTS8rN3zFhfGn/Pl/MLobS0DTfm0omWac5WnFW1Bib31zFzbOm19j6PmFc1kNwhpZWCY1yGn8B7QEx/Eq1VKPTu2FC5nQOkBpQILUotDbNfweHcX2w81z2bEkhCOIvu9lVVxOHFaEyDG2a6l9BlgtZuzeLM2loZogjHPHeO7mG3rzj9mq8kRWEIm+xq1xRaSCFDAS9He9iD+Pq5xJ+7yAKwXNcoQoeaLqRtwCgQABpb5RxTwiMUKy9+L8zXNuDj8sMDDmJbfpbegtsb/28oDi1ToZjaCBdKhQ0BjvrUeCmM1bI/4Rb1OkolV/9rx/YaRYACdUw6+WvMQRr9imJXPh7iIfJB0Mz4O/Ptt80jbd6FCXhz1eqR3svhQlFUi5WMytyXz0zCEPKV0vh/F+w6JcxGezeaC9QAS1ei3bG7xU2XztcWSdPrbYlLFe2WBlXRgHtKPi60=
  file_glob: true
  file: wheelhouse/*.whl
  skip_cleanup: true
  on:
    tags: true
